// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otsrpxfqqnqgicmfxzzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90c3JweGZxcW5xZ2ljbWZ4enptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NzYzOTYsImV4cCI6MjA4MTE1MjM5Nn0.1ujQirCm0xFvxnij3ZYdfnznMw3QsVuuywIZIDvUF8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});